INPUT = "adult_0.7_kid_0.3_home_6_school_300_work_100"
TICKS = 4
BETA = 0.3
GAMMA = 0.14
ALPHA = 0.0
DAYS = 100
SCHOOL_CLOSED_SCHEDULE_ID = 4
OFFICE_CLOSED_SCHEDULE_ID = 5
OUTPUTDIR = "outputs/test"
S_DISCRETIZATION = 0.01
I_DISCRETIZATION = 0.01
POLICY_FILE = "policy.json"
